apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitmap-uploader
  labels:
    app: bitmap-uploader
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bitmap-uploader
  template:
    metadata:
      labels:
        app: bitmap-uploader
    spec:
      containers:
      - name: bitmap-uploader
        image: bitmap-uploader:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m" 